#!/usr/bin/env node

import { promises as fs } from 'fs';

const BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN;
const CHAT_ID = process.env.TELEGRAM_CHAT_ID;
const TRENDING_JSON = 'public/data/trending.json';
const TOP_N = Number(process.env.TELEGRAM_TOP_N || 10);

function escapeHtml(str = '') {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function truncate(str = '', max = 110) {
  if (str.length <= max) return str;
  return `${str.slice(0, max - 1)}…`;
}

async function loadTrending() {
  const raw = await fs.readFile(TRENDING_JSON, 'utf-8');
  return JSON.parse(raw);
}

function buildMessage(data) {
  const repos = (data.repos || []).slice(0, TOP_N);
  const date = new Date(data.date || Date.now());
  const dateText = date.toLocaleDateString('zh-CN', {
    timeZone: 'Asia/Shanghai',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit'
  });

  const lines = [
    `🔥 <b>GitHub Trending Top ${repos.length}</b>`,
    `📅 ${dateText}`,
    ''
  ];

  repos.forEach((repo, index) => {
    const name = `${repo.owner}/${repo.name}`;
    const lang = repo.language ? ` · ${escapeHtml(repo.language)}` : '';
    const growth = repo.growth || repo.starsToday || 0;
    const desc = truncate(escapeHtml(repo.description || 'No description'));

    lines.push(
      `${index + 1}. <a href="${repo.url}">${escapeHtml(name)}</a>`,
      ` ⭐️ +${growth}${lang}`,
      ` ${desc}`,
      ''
    );
  });

  lines.push('🤖 Generated by PeterTrendingBot');
  return lines.join('\n');
}

async function sendTelegramMessage(text) {
  const url = `https://api.telegram.org/bot${BOT_TOKEN}/sendMessage`;
  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      chat_id: CHAT_ID,
      text,
      parse_mode: 'HTML',
      disable_web_page_preview: true
    })
  });

  const result = await response.json();
  if (!response.ok || !result.ok) {
    throw new Error(`Telegram API error: ${JSON.stringify(result)}`);
  }

  console.log('✅ Telegram notification sent');
}

async function main() {
  if (!BOT_TOKEN || !CHAT_ID) {
    throw new Error('Missing TELEGRAM_BOT_TOKEN or TELEGRAM_CHAT_ID');
  }

  const trending = await loadTrending();
  const message = buildMessage(trending);
  await sendTelegramMessage(message);
}

main().catch((error) => {
  console.error('❌ Failed to send Telegram notification');
  console.error(error.message);
  process.exit(1);
});
